title: 笔记
description: > # this means to ignore newlines until "baseurl:"
 笔记.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liangqiyao.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 梁某猿 # add your name
author-img: photo.png # add your photo
about-author: 坚持学习✊ # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: liangqiyao  # add your Github handle
linkedin: # add your Linkedin handle
email: 513098008@qq.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
